import type { Client, ContentItem, Task } from "./types";

const now = new Date().toISOString();

export const sampleClients: Client[] = [
  { name: "Blendbyte", code: "00_BB", short: "BB", order: 0, color: "slate" },
  { name: "Grupo Investe", code: "01_GI", short: "GI", order: 1, color: "blue" },
  { name: "Invest2030", code: "02_I2030", short: "I2030", order: 2, color: "green" },
  { name: "Esportzy", code: "03_ESP", short: "ESP", order: 3, color: "violet" },
  { name: "Leões de Porto Salvo", code: "04_LPS", short: "LPS", order: 4, color: "emerald" },
  { name: "Junta de Freguesia de Porto Salvo", code: "05_JFPS", short: "JFPS", order: 5, color: "orange" },
  { name: "Safe Vanguard", code: "06_SVG", short: "SVG", order: 6, color: "red" },
  { name: "ROOTKey", code: "07_RK", short: "RK", order: 7, color: "cyan" },
  { name: "CAT Power Tools", code: "08_CAT", short: "CAT", order: 8, color: "yellow" },
].map((entry, index) => ({
  id: `sample-client-${index + 1}`,
  name: entry.name,
  client_code: entry.code,
  short_name: entry.short,
  display_order: entry.order,
  logo_url: null,
  color_key: entry.color as Client["color_key"],
  type: entry.name === "Blendbyte" ? "internal" : entry.name === "Grupo Investe" ? "grupo_investe" : "external",
  status: entry.name === "Safe Vanguard" ? "paused" : "active",
  owner_name: ["Carlota", "Carolina", "Sofia", "Guilherme"][index % 4],
  service_type: [
    "Gestão de Redes Sociais",
    "Marketing de Performance",
    "Website / Landing Page",
    "Gestão de Redes Sociais",
    "Branding",
    "Website / Landing Page",
    "Gestão de Redes Sociais",
    "Evento / Cobertura",
    "Newsletter / Email Marketing",
  ][index] as Client["service_type"],
  service_types: [
    [
      "Gestão de Redes Sociais",
    ],
    ["Marketing de Performance"],
    ["Website / Landing Page"],
    ["Gestão de Redes Sociais"],
    ["Branding"],
    ["Website / Landing Page"],
    ["Gestão de Redes Sociais"],
    ["Evento / Cobertura"],
    ["Newsletter / Email Marketing"],
  ][index],
  monthly_value: index % 3 === 0 ? 1200 : null,
  contract_value: index % 3 === 0 ? "1.200€/mês" : null,
  start_date: `2026-07-${String(index + 1).padStart(2, "0")}`,
  contract_duration: index % 2 === 0 ? "6 meses" : "Projeto",
  platforms: index % 2 === 0 ? ["Instagram", "LinkedIn"] : ["Instagram", "Meta"],
  website_url: null,
  instagram_url: null,
  facebook_url: null,
  linkedin_url: null,
  tiktok_url: null,
  youtube_url: null,
  metricool_url: null,
  crm_newsletter_url: null,
  platform_other_url: null,
  drive_url: null,
  figma_url: null,
  meta_url: null,
  google_drive_url: index < 3 ? `https://drive.google.com/drive/folders/sample-${index + 1}` : null,
  onedrive_url: null,
  figma_project_url: index % 2 === 0 ? `https://figma.com/file/sample-${index + 1}` : null,
  content_calendar_url: null,
  final_deliverables_url: null,
  proposal_url: null,
  contract_url: null,
  adjudication_url: null,
  budget_url: null,
  other_documents_url: null,
  brand_assets_url: index === 0 ? "https://drive.google.com/drive/folders/brand-assets" : null,
  setup_checklist: null,
  reporting_url: null,
  initial_briefing_url: null,
  conditions_url: null,
  linkedin_campaign_manager_url: null,
  notes: "Cliente de exemplo. Execute o schema SQL para gravar dados reais no Supabase.",
  created_at: now,
  updated_at: now,
}));

export const sampleContent: ContentItem[] = sampleClients.slice(0, 6).map(
  (client, index) => ({
    id: `sample-content-${index + 1}`,
    client_id: client.id,
    month: "2026-06",
    publish_date: `2026-06-${String(29 + (index % 2)).padStart(2, "0")}`,
    publish_time: index % 3 === 0 ? "09:30" : index % 3 === 1 ? "14:30" : null,
    design_due_date: `2026-06-${String(20 + index).padStart(2, "0")}`,
    copy_due_date: `2026-06-${String(18 + index).padStart(2, "0")}`,
    approval_due_date: `2026-06-${String(24 + index).padStart(2, "0")}`,
    publishing_due_date: `2026-06-${String(28 + (index % 2)).padStart(2, "0")}`,
    design_status: null,
    copy_status: null,
    approval_status: null,
    publishing_status: null,
    needs_design: true,
    needs_copy: true,
    needs_client_approval: index % 2 === 1,
    platform: index % 2 === 0 ? "Instagram" : "LinkedIn",
    format: index % 2 === 0 ? "Reel" : "Carrossel",
    title: `${client.name}: conteúdo semanal`,
    creative_brief: "Peça de exemplo para validar o calendário.",
    copy_text: null,
    description: null,
    status: ["idea", "todo", "in_progress", "ready_to_publish", "published", "archived"][
      index
    ] as ContentItem["status"],
    assignee_name: ["Carlota", "Carolina", "Sofia"][index % 3],
    media_url: null,
    brief_url: index < 2 ? `https://docs.google.com/document/d/sample-brief-${index + 1}` : null,
    media_folder_url: index < 3 ? `https://drive.google.com/drive/folders/media-${index + 1}` : null,
    figma_url: null,
    export_url: null,
    delivery_url: null,
    inspiration_url: null,
    published_url: null,
    internal_review_notes: index === 1 ? "Validar headline antes de fechar arte." : null,
    client_feedback: null,
    is_blocked: index === 2,
    blocker_reason: index === 2 ? "Aguardando imagens finais do cliente." : null,
    recording_date: null,
    notes: null,
    created_at: now,
    updated_at: now,
    clients: {
      id: client.id,
      name: client.name,
      client_code: client.client_code,
      short_name: client.short_name,
      display_order: client.display_order,
      logo_url: client.logo_url,
      color_key: client.color_key,
    },
  }),
);

export const sampleTasks: Task[] = sampleClients.slice(1, 7).map(
  (client, index) => ({
    id: `sample-task-${index + 1}`,
    client_id: client.id,
    title: `${client.name}: preparar próxima semana`,
    type: ["design", "copy", "publishing", "reporting", "operations", "other"][
      index
    ] as Task["type"],
    status: ["todo", "in_progress", "done", "archived", "todo", "in_progress"][
      index
    ] as Task["status"],
    priority: ["normal", "urgent", "normal", "normal", "urgent", "normal"][
      index
    ] as Task["priority"],
    assignee_name: ["Carlota", "Carolina", "Sofia"][index % 3],
    due_date: `2026-07-${String(index + 1).padStart(2, "0")}`,
    related_url: index < 2 ? `https://drive.google.com/drive/folders/task-${index + 1}` : null,
    links:
      index < 2
        ? [{ label: "Pasta Drive", url: `https://drive.google.com/drive/folders/task-${index + 1}` }]
        : [],
    is_blocked: index === 4,
    blocker_reason: index === 4 ? "Falta aprovação do responsável interno." : null,
    notes: null,
    created_at: now,
    updated_at: now,
    clients: {
      id: client.id,
      name: client.name,
      client_code: client.client_code,
      short_name: client.short_name,
      display_order: client.display_order,
      logo_url: client.logo_url,
      color_key: client.color_key,
    },
  }),
);
