"use client";
import { useMemo, useState } from "react";
import { CalendarDays, ChevronLeft, ChevronRight, Pencil, Plus, X } from "lucide-react";
import { cancelVacationRequestAction, createVacationRequestAction, decideVacationRequestAction, deleteCustomHolidayAction, initializeVacationBalancesAction, saveCustomHolidayAction, saveVacationBalanceAction } from "@/lib/actions";
import { calculateBalance, getPortugalNationalHolidays, overlappingWorkingDates, type CustomHoliday, type VacationBalance, type VacationRequest } from "@/lib/vacations";
import type { TeamMember } from "@/lib/types";
import { EmptyState, Panel } from "./ui";

const button = "inline-flex min-h-9 items-center justify-center gap-2 rounded-full border border-[var(--bb-border)] bg-white/75 px-3 text-xs font-extrabold transition hover:bg-[var(--bb-primary-soft)]";
const primary = "inline-flex min-h-10 items-center justify-center gap-2 rounded-full bg-[var(--bb-black)] px-4 text-sm font-extrabold text-white transition hover:bg-[var(--bb-primary)] hover:text-black";
const input = "bb-input text-sm font-semibold";
const labels: Record<string, string> = { pending: "Pendente", approved: "Aprovado", rejected: "Rejeitado", cancelled: "Cancelado" };
const fmt = (date: string) => new Intl.DateTimeFormat("pt-PT", { day: "2-digit", month: "short", year: "numeric" }).format(new Date(`${date}T12:00:00`));

function Modal({ title, close, children }: { title: string; close: () => void; children: React.ReactNode }) { return <div className="fixed inset-0 z-50 grid place-items-center overflow-y-auto bg-black/30 p-4 backdrop-blur-sm"><section className="my-auto w-full max-w-2xl rounded-[22px] bg-white p-5 shadow-2xl"><div className="mb-4 flex items-center justify-between"><h2 className="text-lg font-extrabold">{title}</h2><button className={button} onClick={close} aria-label="Fechar"><X className="size-4" /></button></div>{children}</section></div>; }

function VacationForm({ year, members, admin }: { year: number; members: TeamMember[]; admin: boolean }) { return <form action={createVacationRequestAction} className="grid gap-3"><div className="grid gap-3 sm:grid-cols-2">{admin ? <label className="grid gap-1 text-xs font-extrabold">Pessoa<select name="team_member_id" required className={input}>{members.filter((m) => m.active).map((m) => <option key={m.id} value={m.id}>{m.name}</option>)}</select></label> : null}<label className="grid gap-1 text-xs font-extrabold">Data de início<input className={input} name="start_date" type="date" min={`${year}-01-01`} max={`${year}-12-31`} required /></label><label className="grid gap-1 text-xs font-extrabold">Data de fim<input className={input} name="end_date" type="date" min={`${year}-01-01`} max={`${year}-12-31`} required /></label></div><label className="grid gap-1 text-xs font-extrabold">Nota opcional<textarea className={input} name="employee_note" rows={3} /></label><p className="text-xs font-bold text-[var(--bb-muted)]">Os dias úteis, feriados e saldo são recalculados no servidor antes de guardar.</p><button className={primary}>{admin ? "Registar como aprovado" : "Enviar pedido"}</button></form>; }

function Calendar({ year, requests, holidays, members, admin, ownMemberId }: { year: number; requests: VacationRequest[]; holidays: CustomHoliday[]; members: TeamMember[]; admin: boolean; ownMemberId?: string }) {
  const today = new Date(), [month, setMonth] = useState(today.getFullYear() === year ? today.getMonth() : 0), [selected, setSelected] = useState<string | null>(null);
  const allHolidays = [...getPortugalNationalHolidays(year), ...holidays.filter((h) => h.active).map((h) => ({ date: h.holiday_date, name: h.name, type: h.holiday_type }))];
  const visible = requests.filter((r) => r.status === "approved" || (r.status === "pending" && (admin || r.team_member_id === ownMemberId)));
  const first = new Date(year, month, 1), offset = (first.getDay() + 6) % 7, count = new Date(year, month + 1, 0).getDate();
  const cells = Array.from({ length: Math.ceil((offset + count) / 7) * 7 }, (_, index) => index - offset + 1);
  const details = selected ? { absences: visible.filter((r) => r.start_date <= selected && r.end_date >= selected), holiday: allHolidays.find((h) => h.date === selected) } : null;
  return <Panel className="p-4"><div className="mb-4 flex flex-wrap items-center justify-between gap-2"><h2 className="font-extrabold">Calendário da equipa</h2><div className="flex gap-1"><button className={button} onClick={() => setMonth((m) => Math.max(0, m - 1))}><ChevronLeft className="size-4" /></button><button className={button} onClick={() => setMonth(today.getFullYear() === year ? today.getMonth() : 0)}>Hoje</button><button className={button} onClick={() => setMonth((m) => Math.min(11, m + 1))}><ChevronRight className="size-4" /></button></div></div><h3 className="mb-3 text-center font-extrabold capitalize">{new Intl.DateTimeFormat("pt-PT", { month: "long", year: "numeric" }).format(first)}</h3><div className="min-w-[600px] overflow-hidden rounded-xl border border-[var(--bb-border)]"><div className="grid grid-cols-7 bg-black/5 text-center text-xs font-extrabold">{"Seg Ter Qua Qui Sex Sáb Dom".split(" ").map((d) => <div className="p-2" key={d}>{d}</div>)}</div><div className="grid grid-cols-7">{cells.map((day, index) => { if (day < 1 || day > count) return <div key={index} className="min-h-20 border-t border-r border-[var(--bb-border)] bg-black/[.02]" />; const key = `${year}-${String(month + 1).padStart(2, "0")}-${String(day).padStart(2, "0")}`, abs = visible.filter((r) => r.start_date <= key && r.end_date >= key), holiday = allHolidays.find((h) => h.date === key); return <button type="button" onClick={() => setSelected(key)} key={key} className={`min-h-20 border-t border-r border-[var(--bb-border)] p-1 text-left align-top hover:bg-[var(--bb-primary-soft)] ${abs.length > 1 ? "bg-orange-50" : ""}`}><span className="text-xs font-extrabold">{day}</span>{holiday ? <span className="mt-1 block truncate rounded bg-slate-100 px-1 text-[10px] font-bold">{holiday.name}</span> : null}{abs.slice(0, 2).map((r) => <span key={r.id} className={`mt-1 block truncate rounded px-1 text-[10px] font-bold ${r.status === "approved" ? "bg-[var(--bb-primary)]" : "border border-[var(--bb-primary)]"}`}>{members.find((m) => m.id === r.team_member_id)?.name}</span>)}</button>; })}</div></div>{details ? <div className="mt-3 rounded-xl bg-black/[.035] p-3 text-sm"><strong>{fmt(selected!)}</strong>{details.holiday ? <p>Feriado: {details.holiday.name}</p> : null}{details.absences.map((r) => { const member = members.find((m) => m.id === r.team_member_id); return <p key={r.id}>{member?.name} · {member?.role} · {labels[r.status]}</p>; })}{!details.holiday && !details.absences.length ? <p>Sem ausências nem feriado.</p> : null}</div> : null}</Panel>;
}

export function VacationWorkspace({ year, isAdmin, profileKey, members, balances, requests, holidays }: { year: number; isAdmin: boolean; profileKey: string; members: TeamMember[]; balances: VacationBalance[]; requests: VacationRequest[]; holidays: CustomHoliday[] }) {
  const [modal, setModal] = useState<"request" | "holidays" | null>(null), [editBalance, setEditBalance] = useState<VacationBalance | null>(null);
  const own = members.find((m) => m.name.toLocaleLowerCase("pt") === profileKey), ownBalance = balances.find((b) => b.team_member_id === own?.id), ownSummary = ownBalance && own ? calculateBalance(ownBalance, requests.filter((r) => r.team_member_id === own.id)) : null;
  const activeHolidays = useMemo(() => [...getPortugalNationalHolidays(year), ...holidays.filter((h) => h.active).map((h) => ({ date: h.holiday_date, name: h.name, type: h.holiday_type }))], [year, holidays]);
  const pending = requests.filter((r) => r.status === "pending"), todayKey = new Date().toLocaleDateString("sv-SE"), todayAway = requests.filter((r) => r.status === "approved" && r.start_date <= todayKey && r.end_date >= todayKey);
  return <div className="grid gap-4"><div className="flex flex-wrap items-center justify-between gap-3"><form className="flex items-center gap-2"><input type="hidden" name="tab" value="vacations" /><label className="text-sm font-extrabold">Ano <select name="year" value={year} onChange={(e) => e.currentTarget.form?.requestSubmit()} className={input}>{[year - 1, year, year + 1].map((y) => <option key={y}>{y}</option>)}</select></label></form><div className="flex flex-wrap gap-2"><button className={primary} onClick={() => setModal("request")}><Plus className="size-4" />{isAdmin ? "Registar férias" : "Pedir férias"}</button>{isAdmin ? <button className={button} onClick={() => setModal("holidays")}><CalendarDays className="size-4" />Gerir feriados</button> : null}</div></div>
    {isAdmin ? <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["Pedidos pendentes", pending.length], ["Pessoas de férias hoje", todayAway.length], ["Próximas férias", requests.filter((r) => r.status === "approved" && r.start_date > todayKey).length], ["Sobreposições", requests.filter((r, i) => requests.some((other, j) => j > i && ["pending","approved"].includes(r.status) && ["pending","approved"].includes(other.status) && r.team_member_id !== other.team_member_id && overlappingWorkingDates(r, other, activeHolidays).length)).length]].map(([label, value]) => <Panel className="p-4" key={label}><p className="text-xs font-extrabold text-[var(--bb-muted)]">{label}</p><p className="mt-1 text-2xl font-black">{value}</p></Panel>)}</div> : ownSummary ? <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{[["Total anual", ownSummary.total], ["Aprovados", ownSummary.approvedUsed], ["Pendentes", ownSummary.pendingRequested], ["Disponível", ownSummary.available], ["Após pendentes", ownSummary.projectedAvailable]].map(([label, value]) => <Panel className="p-4" key={label}><p className="text-xs font-extrabold text-[var(--bb-muted)]">{label}</p><p className="mt-1 text-2xl font-black">{value}</p></Panel>)}</div> : <Panel className="p-4"><EmptyState title={`O saldo de ${year} ainda não foi configurado.`} /></Panel>}
    {isAdmin && !balances.length ? <Panel className="p-4"><form action={initializeVacationBalancesAction}><input type="hidden" name="year" value={year} /><button className={primary}>Inicializar saldos de {year}</button></form></Panel> : null}
    {isAdmin ? <Panel className="p-4"><h2 className="mb-3 font-extrabold">Pedidos pendentes</h2>{pending.length ? <div className="grid gap-3">{pending.map((r) => { const m = members.find((x) => x.id === r.team_member_id), b = balances.find((x) => x.team_member_id === r.team_member_id), summary = b ? calculateBalance(b, requests.filter((x) => x.team_member_id === r.team_member_id)) : null; const overlaps = requests.filter((other) => other.id !== r.id && other.team_member_id !== r.team_member_id && ["pending","approved"].includes(other.status) && overlappingWorkingDates(r, other, activeHolidays).length); return <article className="rounded-xl border border-[var(--bb-border)] p-3" key={r.id}><div className="flex flex-wrap justify-between gap-3"><div><strong>{m?.name}</strong><p className="text-sm text-[var(--bb-muted)]">{m?.role} · {fmt(r.start_date)}–{fmt(r.end_date)} · {r.working_days} dias</p>{r.employee_note ? <p className="mt-1 text-sm">{r.employee_note}</p> : null}<p className="mt-1 text-xs font-bold">Saldo: {summary?.available ?? "—"} → {(summary?.available ?? 0) - r.working_days}{overlaps.length ? ` · Sobreposição com ${overlaps.map((o) => members.find((x) => x.id === o.team_member_id)?.name).join(", ")}` : ""}</p></div><div className="flex gap-2"><form action={decideVacationRequestAction.bind(null, r.id, "approved")} onSubmit={(e) => !confirm(`Aprovar ${r.working_days} dias?${overlaps.length ? " Existe sobreposição." : ""}`) && e.preventDefault()}><button className={primary}>Aprovar</button></form><form action={decideVacationRequestAction.bind(null, r.id, "rejected")} onSubmit={(e) => !confirm("Rejeitar este pedido?") && e.preventDefault()}><input name="admin_note" aria-label="Nota de rejeição" placeholder="Nota opcional" className={input} /><button className={button}>Rejeitar</button></form></div></div></article>; })}</div> : <EmptyState title="Sem pedidos pendentes." />}</Panel> : null}
    <Calendar year={year} requests={requests} holidays={holidays} members={members} admin={isAdmin} ownMemberId={own?.id} />
    {isAdmin ? <Panel className="overflow-x-auto p-4"><h2 className="mb-3 font-extrabold">Saldos da equipa</h2><table className="w-full min-w-[850px] text-left text-sm"><thead><tr>{["Pessoa", "Direito", "Transitados", "Ajustes", "Aprovados", "Pendentes", "Disponível", ""].map((h) => <th className="p-2" key={h}>{h}</th>)}</tr></thead><tbody>{balances.map((b) => { const m = members.find((x) => x.id === b.team_member_id), s = calculateBalance(b, requests.filter((r) => r.team_member_id === b.team_member_id)); return <tr className="border-t border-[var(--bb-border)]" key={b.id}><td className="p-2"><strong>{m?.name}</strong><br/><span className="text-xs">{m?.role}</span></td><td>{b.entitled_days}</td><td>{b.carried_over_days}</td><td>{b.adjustment_days}</td><td>{s.approvedUsed}</td><td>{s.pendingRequested}</td><td>{s.available}</td><td><button className={button} onClick={() => setEditBalance(b)}><Pencil className="size-3" />Editar</button></td></tr>; })}</tbody></table></Panel> : null}
    <Panel className="p-4"><h2 className="mb-3 font-extrabold">{isAdmin ? "Histórico" : "Os meus pedidos"}</h2><div className="grid gap-2">{requests.filter((r) => isAdmin || r.team_member_id === own?.id).map((r) => <article className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-[var(--bb-border)] p-3" key={r.id}><div><strong>{isAdmin ? `${members.find((m) => m.id === r.team_member_id)?.name} · ` : ""}{fmt(r.start_date)}–{fmt(r.end_date)}</strong><p className="text-sm">{r.working_days} dias · {labels[r.status]}{r.admin_note ? ` · Resposta: ${r.admin_note}` : ""}</p></div>{(r.status === "pending" || (isAdmin && r.status === "approved")) ? <form action={cancelVacationRequestAction.bind(null, r.id)} onSubmit={(e) => !confirm("Cancelar este pedido sem o apagar?") && e.preventDefault()}><input type="hidden" name="year" value={year}/><button className={button}>Cancelar</button></form> : null}</article>)}</div></Panel>
    {modal === "request" ? <Modal title={isAdmin ? "Registar férias" : "Pedir férias"} close={() => setModal(null)}><VacationForm year={year} members={members} admin={isAdmin} /></Modal> : null}
    {modal === "holidays" ? <Modal title="Gerir feriados adicionais" close={() => setModal(null)}><form action={saveCustomHolidayAction} className="grid gap-3 sm:grid-cols-2"><input className={input} name="holiday_date" type="date" min={`${year}-01-01`} max={`${year}-12-31`} required/><input className={input} name="name" placeholder="Nome" required/><select className={input} name="holiday_type"><option value="municipal">Municipal</option><option value="company">Encerramento</option><option value="custom">Personalizado</option></select><label className="flex items-center gap-2 text-sm font-bold"><input type="checkbox" name="active" defaultChecked/>Ativo</label><button className={primary}>Adicionar feriado</button></form><div className="mt-4 grid gap-2">{holidays.map((h) => <div className="flex items-center justify-between rounded-xl border p-2 text-sm" key={h.id}><span>{fmt(h.holiday_date)} · {h.name} · {h.active ? "Ativo" : "Inativo"}</span><form action={deleteCustomHolidayAction.bind(null, h.id)} onSubmit={(e) => !confirm("Apagar este feriado?") && e.preventDefault()}><input type="hidden" name="year" value={year}/><button className={button}>Apagar</button></form></div>)}</div></Modal> : null}
    {editBalance ? <Modal title="Editar saldo" close={() => setEditBalance(null)}><form action={saveVacationBalanceAction.bind(null, editBalance.id)} className="grid gap-3"><input type="hidden" name="year" value={year}/><div className="grid gap-3 sm:grid-cols-3">{[["Direito anual","entitled_days",editBalance.entitled_days],["Transitados","carried_over_days",editBalance.carried_over_days],["Ajustes","adjustment_days",editBalance.adjustment_days]].map(([label,name,value]) => <label className="grid gap-1 text-xs font-extrabold" key={String(name)}>{label}<input className={input} type="number" step="0.5" name={String(name)} defaultValue={Number(value)}/></label>)}</div><label className="grid gap-1 text-xs font-extrabold">Notas privadas<textarea className={input} name="admin_notes" defaultValue={editBalance.admin_notes ?? ""}/></label><button className={primary}>Guardar saldo</button></form></Modal> : null}
  </div>;
}
